# Generated by Django 4.2.4 on 2023-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('eduaction', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=225)),
                ('address', models.CharField(max_length=64)),
                ('postalCode', models.CharField(max_length=64)),
            ],
        ),
    ]
