# Generated by Django 4.2.4 on 2023-08-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='eduaction',
            new_name='education',
        ),
    ]
