openapi: 3.0.3
info:
  title: PeopleList API
  version: 1.0.0
paths:
  /api/all:
    get:
      operationId: api_all_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
  /api/createNew:
    post:
      operationId: api_createNew_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/People'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/People'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/People'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/delete/{id}:
    delete:
      operationId: api_delete_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/templateCreate:
    post:
      operationId: api_templateCreate_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/People'
          application/x-www-form-urlencoded:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/People'
          multipart/form-data:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/People'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/update/{id}:
    put:
      operationId: api_update_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: {}
          application/x-www-form-urlencoded:
            schema:
              type: object
              additionalProperties: {}
          multipart/form-data:
            schema:
              type: object
              additionalProperties: {}
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    People:
      type: object
      properties:
        name:
          type: string
          maxLength: 64
        position:
          type: string
          maxLength: 64
        department:
          type: string
          maxLength: 64
        education:
          type: string
          maxLength: 64
        degree:
          type: string
          maxLength: 64
        email:
          type: string
          format: email
          maxLength: 225
        address:
          type: string
          maxLength: 64
        postalCode:
          type: string
          maxLength: 64
      required:
      - address
      - degree
      - department
      - education
      - email
      - name
      - position
      - postalCode
    Query:
      type: object
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        name:
          type: string
          maxLength: 64
        position:
          type: string
          maxLength: 64
        department:
          type: string
          maxLength: 64
        education:
          type: string
          maxLength: 64
        degree:
          type: string
          maxLength: 64
        email:
          type: string
          format: email
          maxLength: 225
        address:
          type: string
          maxLength: 64
        postalCode:
          type: string
          maxLength: 64
      required:
      - address
      - degree
      - department
      - education
      - email
      - name
      - pk
      - position
      - postalCode
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
